### ISSUE TITLE
dcrd component should be required for the Paymetheus component

### ISSUE THREAD

**Issue by jrick** [decred/decred-windows-installer#13]
Otherwise the launcher (which is in the Paymetheus component) won't be able to start dcrd if it's not found.

**Comment by jrick** [comment]
Or we move the launcher to its own component, and make it depend on both dcrd and Paymetheus.

**Comment by marcopeereboom** [comment]
I am going to treat dcrd the same as dcrwallet in the next release.  So it'll be non-optional and bundled the same.
