### ISSUE TITLE
Verify msis

### ISSUE THREAD

**Issue by marcopeereboom** [decred/decred-windows-installer#17]
Verify installation win 7:
- [x] 64bit installer
- [ ] 32bit installer

Verify installation win 10:
- [x] 64bit installer
- [ ] 32bit installer

Verify upgrade win 7:
- [x] 64bit
- [ ] 32bit

Verify upgrade win 10:
- [x] 64bit
- [ ] 32bit

Verify the following functionality win 7:
- [x] clean startup (all directories removed)
- [x] upgrade wit prior .conf files

Verify the following functionality win 10:
- [x] clean startup (all directories removed)
- [x] upgrade wit prior .conf files

**Comment by jolan** [comment]
"Latest block" stays on 0 for me on Win 10 64-bit.  dcrd is definitely syncing in the background.  Wiped everything and tried again and was able to reproduce.

**Comment by jolan** [comment]
Also, when I go back into Paymetheus and enter my Public Passphrase it says "Incorrect passphrase".  The passphrase I used is "test". Reproduced this a second time too.

**Comment by jrick** [comment]
@jolan for the latest block, that has always been the case.  This release doesn't even contain any significant changes to paymetheus, it's all work on the go tools.

I will try to reproduce the public passphrase issue.

**Comment by jolan** [comment]
Hmm, odd, I remember it counting up before.

**Comment by jcvernaleo** [comment]
I tested and at least for basic clicking around, win7 64bit upgrade works.

**Comment by jcvernaleo** [comment]
Clean install for win7 64bit good too.

**Comment by jolan** [comment]
I let 0.4.0 sync to 60k/70k and got tired of waiting so I let it close cleanly. Then I upgraded to 0.5.0 and wallet barfed:

![wallet error](https://i.imgur.com/f0b9qYt.png)

Re-opening Paymetheus worked ok.

**Comment by marcopeereboom** [comment]
@jolan please open an issue for that crash.
