### ISSUE TITLE
Decred Directory Rearrangement and dcrctl.exe missing

### ISSUE THREAD

**Issue by JasonSome** [decred/decred-windows-installer#26]
I used to have an installation by msi of Decred 0.4.0 that had the dcrctl and dcrd binaries inside the "Dcrd" subdirectory and the dcrwallet binary inside the "Paymetheus" subdirectory. After upgrading today to 0.5.0 by msi I have the dcrctl.exe completely missing from all subdirectories and dcrd and dcrwallet binaries both inside the "Paymetheus" subdirectory, along with an empty "Dcrd" subdirectory. This seems not to be planned, therefore something must have gone wrong during 0.5.0 msi build (?)

**Comment by marcopeereboom** [comment]
The directory structure changed around because dcrd (and therefore dcrctl) is no longer optional.  It lives inside the same dir now as paymetheus and dcrwallet.

**Comment by JasonSome** [comment]
@marcopeereboom

1) However, dcrctl isn't installed by the current 0.5.0 msi installer. (confirmed by image upload on IRC chat) So, the issue still remains.

2) Also, I cannot understand why then almost everything is installed inside a "Paymetheus" directory. Shouldn't they be in the root directory? Because dcrd isn't Paymetheus.

**Comment by marcopeereboom** [comment]
@JasonSome I apologize this *is* a bug.  I broke this and I will fix it next release.
