### ISSUE TITLE
Verify MSIs

### ISSUE THREAD

**Issue by marcopeereboom** [decred/decred-windows-installer#8]
Verify installation win 7:
- [x] 64bit installer
- [ ] 32bit installer

Verify installation win 10:
- [x] 64bit installer
- [x] 32bit installer

Verify upgrade win 7:
- [x] 64bit
- [ ] 32bit

Verify upgrade win 10:
- [x] 64bit
- [x] 32bit

Verify the following functionality win 7:
- [x] clean startup (all directories removed)
- [x] upgrade wit prior .conf files

Verify the following functionality win 10:
- [x] clean startup (all directories removed)
- [x] upgrade wit prior .conf files

**Comment by jrick** [comment]
Verified all the MSI tasks work on Win10 amd64

**Comment by jolan** [comment]
Re-verified clean install works on Win10 amd64.

**Comment by jolan** [comment]
Verified all taks work on Win7 amd64.

**Comment by jcvernaleo** [comment]
I went through some of them on Win7 amd64 as well.

**Comment by marcopeereboom** [comment]
Verified x86 install + apps.

No one has windows 7 x86 so we'll assume win 7 x64 testing covers it.
